version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - ${RMQ_PORT}:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}
      - RABBITMQ_NODE_PORT=${RMQ_PORT}

volumes:
  rabbitmq_data:
